tasks:
  - before: echo "Start prebuild" && date && sudo apt-get update && echo "Ende prebuild update" && date && sudo apt-get install -y ccache && echo "Ende prebuild install" && date && ccache -M 11G && echo "Ende prebuild" && date
# libclucene-core1v5 llvm clang clang-tools git build-essential junit4 libkrb5-dev nasm graphviz python3 python3-dev qtbase5-dev libkf5coreaddons-dev libkf5i18n-dev libkf5config-dev libkf5windowsystem-dev libkf5kio-dev autoconf libcups2-dev libfontconfig1-dev gperf default-jdk doxygen libxslt1-dev xsltproc libxml2-utils libxrandr-dev bison flex libgtk-3-dev libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev ant ant-optional
# && scan-build --use-cc=clang --use-c++=clang++ ./autogen.sh --enable-debug && scan-build --use-cc=clang --use-c++=clang++ ./configure && mkdir /tmp/libreoffice && scan-build --use-cc=clang --use-c++=clang++ -o /tmp/libreoffice make -j4
#    -command: echo "TESTGitpod   "  
ports:
  - port: 8000
    onOpen: open-preview
  - port: 3306
    onOpen: ignore
github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
vscode:
 extensions:
  - ms-vscode.makefile-tools@0.3.1
#workspaceLocation: "."
image: gitpod/workspace-full-vnc